"""initial schema

Revision ID: 6281c9d3d1b6
Revises: 
Create Date: 2025-12-02 01:16:41.520657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6281c9d3d1b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_subject_id'), 'courses', ['subject_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_title', sa.String(), nullable=False),
    sa.Column('qualification', sa.String(), nullable=False),
    sa.Column('subject_title', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('paper_id_code', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('paper_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id_code', name='uq_exam_paper_id_code')
    )
    op.create_index(op.f('ix_exam_papers_exam_id'), 'exam_papers', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_papers_paper_id_code'), 'exam_papers', ['paper_id_code'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('unit_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'unit_index', name='uq_unit_course_index')
    )
    op.create_index('ix_unit_course_unitindex', 'units', ['course_id', 'unit_index'], unique=False)
    op.create_index(op.f('ix_units_course_id'), 'units', ['course_id'], unique=False)
    op.create_table('user_question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question_id_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_marked', sa.Boolean(), nullable=False),
    sa.Column('canvas_maths', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('canvas_paths', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('canvas_textboxes', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('origin_ref', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id_code', 'created_at', name='uq_user_question_attempt')
    )
    op.create_index('ix_attempt_created', 'user_question_attempts', ['created_at'], unique=False)
    op.create_index('ix_attempt_question', 'user_question_attempts', ['question_id_code'], unique=False)
    op.create_index('ix_attempt_user_question', 'user_question_attempts', ['user_id', 'question_id_code'], unique=False)
    op.create_index(op.f('ix_user_question_attempts_question_id_code'), 'user_question_attempts', ['question_id_code'], unique=False)
    op.create_index(op.f('ix_user_question_attempts_subject_id'), 'user_question_attempts', ['subject_id'], unique=False)
    op.create_index(op.f('ix_user_question_attempts_user_id'), 'user_question_attempts', ['user_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('topic_index', sa.Integer(), nullable=False),
    sa.Column('topic_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'topic_index', name='uq_topic_unit_index')
    )
    op.create_index('ix_topic_unit_topicindex', 'topics', ['unit_id', 'topic_index'], unique=False)
    op.create_index(op.f('ix_topics_unit_id'), 'topics', ['unit_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('lesson_index', sa.Integer(), nullable=False),
    sa.Column('lesson_id_code', sa.String(), nullable=False),
    sa.Column('lesson_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'lesson_index', name='uq_lesson_topic_index')
    )
    op.create_index('ix_lesson_code', 'lessons', ['lesson_id_code'], unique=False)
    op.create_index('ix_lesson_topic_lessonindex', 'lessons', ['topic_id', 'lesson_index'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_id_code'), 'lessons', ['lesson_id_code'], unique=False)
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'chunk_index', name='uq_chunk_lesson_index')
    )
    op.create_index('ix_chunk_lesson_chunkindex', 'chunks', ['lesson_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_chunks_lesson_id'), 'chunks', ['lesson_id'], unique=False)
    op.create_table('practice_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('topic_index', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sets_course_id'), 'practice_sets', ['course_id'], unique=False)
    op.create_index(op.f('ix_practice_sets_lesson_id'), 'practice_sets', ['lesson_id'], unique=False)
    op.create_index('ix_practiceset_course_unit_topic', 'practice_sets', ['course_id', 'unit_index', 'topic_index'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id_code', sa.String(), nullable=False),
    sa.Column('origin_type', sa.String(), nullable=False),
    sa.Column('exam_paper_id', sa.Integer(), nullable=True),
    sa.Column('practice_set_id', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('question_stem', sa.Text(), nullable=True),
    sa.Column('question_stem_diagram', sa.Text(), nullable=True),
    sa.Column('validation_comment', sa.Text(), nullable=True),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id_code', 'origin_type', name='uq_question_code_origin')
    )
    op.create_index('ix_question_code_origin', 'questions', ['question_id_code', 'origin_type'], unique=False)
    op.create_index(op.f('ix_questions_exam_paper_id'), 'questions', ['exam_paper_id'], unique=False)
    op.create_index(op.f('ix_questions_origin_type'), 'questions', ['origin_type'], unique=False)
    op.create_index(op.f('ix_questions_practice_set_id'), 'questions', ['practice_set_id'], unique=False)
    op.create_index(op.f('ix_questions_question_id_code'), 'questions', ['question_id_code'], unique=False)
    op.create_table('question_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_part', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('markmax', sa.Integer(), nullable=False),
    sa.Column('markscheme', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('primary_lesson_id', sa.Integer(), nullable=True),
    sa.Column('item_id_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['primary_lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id_code', name='uq_item_code')
    )
    op.create_index(op.f('ix_question_items_difficulty'), 'question_items', ['difficulty'], unique=False)
    op.create_index(op.f('ix_question_items_item_id_code'), 'question_items', ['item_id_code'], unique=False)
    op.create_index(op.f('ix_question_items_primary_lesson_id'), 'question_items', ['primary_lesson_id'], unique=False)
    op.create_index(op.f('ix_question_items_question_id'), 'question_items', ['question_id'], unique=False)
    op.create_table('item_chunk_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['question_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_chunk_links_chunk_id'), 'item_chunk_links', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_item_chunk_links_item_id'), 'item_chunk_links', ['item_id'], unique=False)
    op.create_index('ix_itemchunk_item_chunk', 'item_chunk_links', ['item_id', 'chunk_id'], unique=False)
    op.create_table('item_lesson_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['question_items.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_lesson_links_item_id'), 'item_lesson_links', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_lesson_links_lesson_id'), 'item_lesson_links', ['lesson_id'], unique=False)
    op.create_index('ix_itemlesson_item_lesson', 'item_lesson_links', ['item_id', 'lesson_id'], unique=False)
    op.create_table('question_item_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['question_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'source_file', 'source_kind', name='uq_item_source')
    )
    op.create_index('ix_prov_item', 'question_item_provenance', ['item_id'], unique=False)
    op.create_index(op.f('ix_question_item_provenance_item_id'), 'question_item_provenance', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_item_provenance_item_id'), table_name='question_item_provenance')
    op.drop_index('ix_prov_item', table_name='question_item_provenance')
    op.drop_table('question_item_provenance')
    op.drop_index('ix_itemlesson_item_lesson', table_name='item_lesson_links')
    op.drop_index(op.f('ix_item_lesson_links_lesson_id'), table_name='item_lesson_links')
    op.drop_index(op.f('ix_item_lesson_links_item_id'), table_name='item_lesson_links')
    op.drop_table('item_lesson_links')
    op.drop_index('ix_itemchunk_item_chunk', table_name='item_chunk_links')
    op.drop_index(op.f('ix_item_chunk_links_item_id'), table_name='item_chunk_links')
    op.drop_index(op.f('ix_item_chunk_links_chunk_id'), table_name='item_chunk_links')
    op.drop_table('item_chunk_links')
    op.drop_index(op.f('ix_question_items_question_id'), table_name='question_items')
    op.drop_index(op.f('ix_question_items_primary_lesson_id'), table_name='question_items')
    op.drop_index(op.f('ix_question_items_item_id_code'), table_name='question_items')
    op.drop_index(op.f('ix_question_items_difficulty'), table_name='question_items')
    op.drop_table('question_items')
    op.drop_index(op.f('ix_questions_question_id_code'), table_name='questions')
    op.drop_index(op.f('ix_questions_practice_set_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_origin_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_paper_id'), table_name='questions')
    op.drop_index('ix_question_code_origin', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_practiceset_course_unit_topic', table_name='practice_sets')
    op.drop_index(op.f('ix_practice_sets_lesson_id'), table_name='practice_sets')
    op.drop_index(op.f('ix_practice_sets_course_id'), table_name='practice_sets')
    op.drop_table('practice_sets')
    op.drop_index(op.f('ix_chunks_lesson_id'), table_name='chunks')
    op.drop_index('ix_chunk_lesson_chunkindex', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson_id_code'), table_name='lessons')
    op.drop_index('ix_lesson_topic_lessonindex', table_name='lessons')
    op.drop_index('ix_lesson_code', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_topics_unit_id'), table_name='topics')
    op.drop_index('ix_topic_unit_topicindex', table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_user_question_attempts_user_id'), table_name='user_question_attempts')
    op.drop_index(op.f('ix_user_question_attempts_subject_id'), table_name='user_question_attempts')
    op.drop_index(op.f('ix_user_question_attempts_question_id_code'), table_name='user_question_attempts')
    op.drop_index('ix_attempt_user_question', table_name='user_question_attempts')
    op.drop_index('ix_attempt_question', table_name='user_question_attempts')
    op.drop_index('ix_attempt_created', table_name='user_question_attempts')
    op.drop_table('user_question_attempts')
    op.drop_index(op.f('ix_units_course_id'), table_name='units')
    op.drop_index('ix_unit_course_unitindex', table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_exam_papers_paper_id_code'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_exam_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_table('users')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_courses_subject_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
